# Generated by Django 2.1.1 on 2018-09-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsPost', '0002_question_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-timestamp']},
        ),
    ]
