# Generated by Django 2.1.1 on 2018-09-21 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportsPost', '0004_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
