# Generated by Django 2.1.1 on 2018-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsPost', '0005_question_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
